### PR TITLE
Adding features that it desparately needed

### PR DESCRIPTION
**Pull request by JMVRy**
Adding a few features that are nice to have:
1. Panning/Zooming. Now you can pan in the Spine Editor and Image Viewer with WASD (mouse panning maybe sometime later? also arrow keys didn't want to work for some reason)
2. Order selecting. Now you can choose which body parts get shown during the animation in Spine Editor. This is mostly to help with the Jax/Remy combined animation overlapping.
3. Image Viewer. No longer do you need to export an image just to view it, as you can view it in a special viewer in the editor! Just double-click the image to view!
4. Any bugs that I have accidentally added, and have yet to find or remember!

### CODE REVIEW

**Comment by araghon007** [comment]
I thought #4 talked about bugs I added at first, had to re-read that. I know there's at least 1 bug I fixed in a local repo, but never bothered to push, forgot what it was already.

I intentionally removed the spine runtime DLLs from any release I sent out and left the viewer in such a sorry state as to not anger Esoteric, since I highly doubt this adheres to their license agreement (~~I haven't agreed to anything~~). Forgot it's still a NuGet package, and they haven't gone after me yet so uhh

~~Also isn't using OpenGL for image viewing a bit overkill~~

Other than that, nice. I want to work on Amorous modding again someday, but there's lots and lots of projects I also need to tend to and I haven't in a good year or so. I'll merge if you don't have anything else to add.

**Comment by araghon007** [comment]
Oh yeah, also just to cover my ass, where'd you get the play and pause icons from?

**Comment by JMVRy** [comment]
The OpenGL for image viewing was just because I basically just copied the code you used for the Spine Editor, and just used the "DrawBackground" function lmao

The play/pause icons I grabbed from DuckDuckGo under "Public domain", but the exact link is [https://svgsilh.com/image/1956799.html](https://svgsilh.com/image/1956799.html), which it says is CC0

**Comment by JMVRy** [comment]
But yeah, I'm just lucky that I've held enough patience to add these features. Most of the time I just give up on a project soon after I get the idea, but somehow I've stuck with this and added some nice features.

But I don't have anything else I want to work on right now. Maybe I'll figure out importing the user's character (to change the animation's colors and whatnot) some other time, or something else, but not soon.

**Pull request merged**
